version: '3.8'

services:
  konsi_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - konsi
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PWD=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=konsi

  rabbitmq:
    image: rabbitmq:latest
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
    networks:
      - konsi

  konsi_worker:
    build: ./konsi_worker
    depends_on:
      - rabbitmq
    networks:
      - konsi
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PWD=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=konsi

  postgres:
    image: postgres:14.1-alpine
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_DB=konsi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - konsi

networks:
  konsi:
    driver: bridge
