version: '3.8'

services:
  konsi_api:
    build:
      context: ./konsi_api
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./konsi_api:/konsi_api
    depends_on:
      - rabbitmq
      - postgres
      - redis
    ports:
      - 8000:8000
    networks:
      - konsi
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PWD=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=konsi
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
      - RABBITMQ_DEFAULT_HOST=rabbitmq
      - REDIS_HOST=redis

  rabbitmq:
    image: rabbitmq:latest
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
    networks:
      - konsi

  redis:
    image: redis:latest
    container_name: 'redis'
    ports:
      - 6379:6379
    networks:
      - konsi

  konsi_worker:
    build:
      context: ./konsi_worker
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./konsi_worker:/konsi_worker
    depends_on:
      - rabbitmq
      - postgres
      - redis
    networks:
      - konsi
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PWD=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=konsi
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
      - RABBITMQ_DEFAULT_HOST=rabbitmq
      - REDIS_HOST=redis

  postgres:
    image: postgres:14.1-alpine
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_DB=konsi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - konsi

networks:
  konsi:
    driver: bridge
